### ISSUE TITLE
Still crapping out on 20G heap

### ISSUE THREAD

**Issue by jonross** [jonross/trilby#33]
```
Exception in thread "main" java.lang.OutOfMemoryError: Direct buffer memory
    at java.nio.Bits.reserveMemory(Bits.java:658)
    at java.nio.DirectByteBuffer.<init>(DirectByteBuffer.java:123)
    at java.nio.ByteBuffer.allocateDirect(ByteBuffer.java:306)
    at trilby.nonheap.NHUtils$.alloc(NHUtils.scala:36)
    at trilby.nonheap.HugeArray$OfInt.<init>(HugeArray.scala:6)
    at trilby.graph.CompactIntGraph$Edges.<init>(CompactIntGraph.scala:82)
    at trilby.graph.CompactIntGraph.<init>(CompactIntGraph.scala:48)
    at trilby.hprof.Heap$$anonfun$optimize$5.apply$mcV$sp(Heap.scala:308)
    at trilby.hprof.Heap$$anonfun$optimize$5.apply(Heap.scala:308)
    at trilby.hprof.Heap$$anonfun$optimize$5.apply(Heap.scala:308)
    at trilby.util.Oddments$.time(Oddments.scala:110)
    at trilby.hprof.Heap.optimize(Heap.scala:307)
```

**Comment by jonross** [comment]
Fixed.  Can read 20G heap with --g1 -Xmx20g, no off-heap memory.
Had to make dominator link compression non-recursive.  :-(
